"""fix target_calories column name

Revision ID: 59961e568d84
Revises: 
Create Date: 2026-10-01 22:04:09.902729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59961e568d84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('foods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('off_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein_per_100g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs_per_100g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat_per_100g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('off_code')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('bmr', sa.Integer(), nullable=False),
    sa.Column('tdee', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_protein_g', sa.Integer(), nullable=False),
    sa.Column('target_carbs_g', sa.Integer(), nullable=False),
    sa.Column('target_fat_g', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('diary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'food_id')
    )
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_entries_entry_date'), ['entry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_entries_entry_date'))

    op.drop_table('diary_entries')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('profiles')
    op.drop_table('foods')
    op.drop_table('users')
    # ### end Alembic commands ###
