"""update food schema

Revision ID: 915517b7dbee
Revises: 59961e568d84
Create Date: 2026-10-03 15:27:49.645536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915517b7dbee'
down_revision = '59961e568d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_100ml', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('calories_per_100ml')

    # ### end Alembic commands ###
